---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: emqx-credentials
  namespace: mqtt
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    EMQX_DASHBOARD__DEFAULT_PASSWORD: AgAQQiAIwFG+cNx7FVotxA+Ceo2tfoLGW3EWQzwE7YVFqthj4y58aa/LACZyRDlDUjQ0I23F87KR+2/HjREtyUDPTgQyMddfJVofxESpiCV1806ASfxO1hcuBAVxNYktXM3YGLXsXyH1Vari0MpepXhJG4gHfzxrt0NN/V4a29mzBSaV/0VPipb5e8bcuFXJZwTsO6ZDhie8WOUdRrIvMRaWqyysuEYH7EyvTEyBtDuC09nIuMl32rD8YMmaB8PspvX+dL0eQ9KMjwfi2rCd3U+TTO1qnH5M2V+D1HS0KUw2a0J3wNDACMGOAH/qTuTSKwyYJltj6Rp2uLGH78hoCiVvMt18DKEvjomddTp1Pen28mrF98nz0ueeib+vV3EdfW8y3aD1rkkl3wlK49xQooRAEDsL5PInKuwDbGrEgd3ndebkDtk9JSfarwIVJqVArXB6x27uJbmFR0YdI5kt93nXqr+QXzXr7975SMhXTkLDb0nXPPiQiFzAR/0EvlAxAsa9CEXjNWxf1OYopFvIFleBf/b5jeHs3QKenvTwMuePk2MblqTJiJDTLO8zBTn7NiR0osPzgyu9cW57Ew6O/itgrrnJH2fTR75OAjZsYmGfOt+y0VtJ/EHxUP6hyTYHHgydIORFnv08OBT4rpfwSQKNuQlUT3o5cjH8K48j6/GOg9gCKLpY7pssZClv38AjXRzHwcQWXJl2pdcPWgsB7prWTeSU6MrwquU=
    EMQX_DASHBOARD__DEFAULT_USERNAME: AgAKmQyRKLFNL7AKy2efp/rU30GrQJoHqcnmeAi7Ys4MjsfLxWJ9zvihMecagrMSqT+QKBjfeSW8X6//Qb6aRRuLqQkwWYrm1Zq/zD2L4rJVONTVKcej6PbD3nuFXXMskgsrslI7eYj6D3gGwTAyLNBDaNa8uwZ+GeSsP2NPR8BaIGI9WrSyF/ShHpqY9BM6xrMYeACbthOGCkF2kD5vzyIViV8gI/9dxouzbb+mhxcWjtj355Qoe/DSD/g/eVUqnSm6RhC/f9/ZdJj2FG4ZCeyc61ErV/DcYkSYM1aW/hUjK6r6yeyphBW7mw9vTOmYngZqkuLjXdYTXORG1cjpfbSZWPHR05uzGDz3OPJn+WrYa/6Q2QkVQqIoxzf7UXJhFscIKw4xloTTCVmEhKCL5g6N2rhFq0NCi8cXV8fdxT8VPT4D7B3DuG+zn///otRRkZLpJR73glJmdxKbHbRwFAQceGGX2hWP0nL6z16u8J7Lvo1vYiAoqK1JdoxavSxlff5wLSrAwrh82Nz7B8a3fc+dno1HKyltm6XskTDvGX5IhT6By4RGsxvzL8BOIwCaqISbaWyzeyz+M2DO7zcNQ89P47MS7zu3GEBgliC+RkYMiqh8OR4GsYWJVs4LXxZtTnT4KyH9+QttDtlI47kdiUfcP/McewWD3lxl1dmMY98HnNSiW4EEyYkf+OuhCyiEtoXG/7/b7A==
  template:
    metadata:
      name: emqx-credentials
      namespace: mqtt
    type: Opaque
