apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-iot-miot-bridge-sandbox
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      path: helm-charts/iot-applications
      helm:
        releaseName: api-iot-miot-bridge
        valueFiles:
          - $values/helm-values/iot/miot-bridge.yaml
          - $values/helm-values/iot/sandbox/miot-bridge.yaml
          - $values/helm-values/iot/sandbox/variables.yaml
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      path: k8s-manifests/iot/sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true