apiVersion: v2
name: iot-applications
description: A Helm chart for IoT applications
type: application
version: 0.0.1
# appVersion: 0.0.1
maintainers:
  - name: Radoslav Irha
    email: radoslav.irha@gmail.com