---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-credentials
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    api-key: AgANZUmZdqwqrO+vIK39UnJDc0vKZpSMXGbNSujSut4iVtvnQUA+93/A6iuQtHtQFuhdpffwkx6BcFAXaXdnVElyijizvrtiQ7j+Np/9xZwtD2Tg12rSn31Y8E/KIfMI37vsUl1IOFVZs0QfxIStypn7WdFNpUANGQSJcewDlROrJGGoxyY2HsaVTiy59jKgW/lJZMpCW3EbN66UBIJOm6o8jrfr2vIv/qCb3FJAOI1SjV5Gs3g5h5mAAeEL1RTJm8p5eePDGes+gJ/zlAHRvMZxhMlqAJ+2VLPkVEphHtOxYMCgFsKf3ekAkKWveYp3h9gnoSEFwnB8N7FsXYj+XAi7tHazsfW8D1b8zv6qqFUK9T67aJKh0F4IMLYnSl2fMY4vVHSjmxFbJoAlATIELWiZnLxv7Mv5SVRAizL4PSLYl7WFsGvg2LP35G8FL6eaY6WGCiblTlq3tjzP63ex1c0IBkpymsuMZ7V/iCyKoAHstPjWSPmtrDrJUiVx5QAkAORhIyhBOnuQ83ImxaIbT7/pud7S3Q7B7JI1ZHWkzMWCqs/9XvyDr9kBL0TAoOjrIhCiSis0hHYoIR/in2p4FwDjdXpn4UO5QlRTo9aPQ/CaMSoGauZNbG83Gcvs12pakgeP0FMKlTiugAwRkuJtINIWF2P88H6ivpR8xVkQKphSF+ZDWDCY7RmBDxVEUwWEBW++lPXm/ag28Ijqc4Jevmm/P2i1bec2SS0Vi1Eg0Obeug==
  template:
    metadata:
      name: unifi-credentials
      namespace: external-dns
    type: Opaque
