---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegraf-influxdb2-credentials
  namespace: telegraf
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    INFLUXDB2_TOKEN: AgAC7mLSjaRMS1q6PG/mzWtNolsD/EaCLQIJ5dnK8FljVHib7yYotT5krLUegpDB1oTDO2fYScFoZYtLpfH+G16Nh0yf2sQGcdWq97lFEbo40wrJiap+HCHxFLB6Q2VPOM+2OvwL11zBdIDAWpwa31RtJLlMtgnWGaOMI0jziXXw2/CQIK28Iy9zR2sj0PQxnHS8iFB6RVl5r4gS9I3p4svFukosCpUG3UWPR+9/pD4RtJnAVqSz7RkRQsLIEI2ChjMaGU5+qNQiLefUOofquS+Ttj5VsNxL1X//Enm0CVwHVicyOQI0C+8lb1bhbQkVCkOyKSfZMR5SMRFvfDYxd1PN6xCia7L0UoI6LphdojV2sIzckVikHjP6E27lpRopEaUDpSJO7m2YmL9zhGiPvPl8vfis5ONIKPI8cpw3ER+E1SjjtZog/+e+fsDg0oDS+3+8mpzd/g47vX9TuMuZY5d7RfCN130W+pYEM/Gqxj7rne9WZhiJIIpWvzKMXhvp5Vh7uZRUe90jQLLu/Zj5De931TF47D/Eg1WK5JcyhVv7KvhHgeZLBj4A3YS+V57hkee5l4QlvYfEjxZhVW3evwBylRU8KcZVE+0ApVt42FNp0HW4bk/CrqX1sKrME4f1D682mLCskhdd96Ve22CODhiC+DMWhsVs4r0Yb2yFxQqj22b1eU9c8PXuGp+0ulMQVjlWa+J5uDSphMaODEIsK/lh8QtDEN7HUwhmpHfUSdRv8N05Hj86ayx/hmv3knbn8csKtbUcE2hAUNujmtdZb6RQqpjgBNk1seD2DA7wd3NRS+Al1tm8eWU1
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-100"
      name: telegraf-influxdb2-credentials
      namespace: telegraf
    type: Opaque
