---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegraf-mqtt-credentials
  namespace: telegraf
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    MQTT_PASSWORD: AgCmaiwVIHRqHqpOidLO0KLAWp+J2aXBnsWMNucsBbpYdZywuAJbfFCS9FQwX+SpDl8N4/OH6cwGMQTemrsCGb59k+2UiM3PgAS0aN+QOqKJ96BBpvlenW71LOLkzSwkwKykqTVvPstppvPLPW9SrWMGGrn0KCIMSQQO+hnVdabjEFgejo/kyZPSB6CfjEofyysitPHLoufffUxw5ivxI9l7QFOw6uNkicjJiRgpWF2TgQmgicNGb1HVbUtyBYC4/yYmSpy4lIfhnRc3jhDGqZjTlhiAF4e6XpQReaPpj3hjkxdNfktKPDH+WMyS+nt7j5lrrn/t2uT/YI+tegeKkRyDH7R2GKqLqdMxEGtE2k74rUPgX6QvWXagKMK42MqUqsvNbIwxzCRlY8M0BnbJagVzdXTkdNjIdXXigJXpBxrE9cJX5MKlykRVWg1L8PpIEq6BeorEr0RqJMizKIRwegev7mb+hY76mdgA44gXOdhUPGeFPV7NkV/kkNglVWhy1cqu30cwCjIYM9lzRelUjau1FJYRQviQllyn97nsD7JpKOsLe5ytr5M87Yr0b8Lg0bmGNNxNh28QD9Unoa6as7b3KYvNJRuBqFFRFXb3CNT1i8PrSKJBOG7dgLSmXl149b7bBmc1KW3RxoC00Q9imZ3MhMGVZz8KL7fFVaRMYtvwtzpDb5+nLNbSV+rUkGbA9Z2LFMbN3afIHaSH4hb0SkgA6fSmUh4/5Y0UDGJ9sZV/swRxOZ4nz4LEQmt8KA==
    MQTT_USERNAME: AgCIqyh9Imi0ytbPFaVxlUZvRvAzMGO3pJM11GsJT7WwvbWXN7ZyV0SLVGP3d3fUrbI9xJPuOU3RD/5pE0MgRCS71xGXR61eNrBj8/IuR7Aw4qiBNcn1MpVlhX0sfVC8wy0nbzYyVjXbvhWT1vpNXtQd81wBQtFAEJnvVzzH5bZXIhF+18D1XHiVd5+0dw+n2T+5Aq0yJDtXL17O4Mz8Jteib6BAismDGdEpleswEW+ghug7Vd50v91XqNMS/UX3fJFUYkjoQKyR/r6ACCtaK3b6/7OP+mTXtXxuq1znysef15pu5kbHN1nLh5JCvLFPgvzC/i78Ciw3XF+f/L8B3iq/TAO930kyZH1GIy4aP7Fc3N3+2VwqMj9Fcxfvclfb7tIH6hBBGfyQjmhikrYkePdmDE1tf7BT/klV3JnJ20hCJU1i5shjEZ4ih3Kavfn9mAw7F3ZfJ2eHSSCk/lvPrrlyx4CWq9R49HhAFFfuvKLrKoBcZlp3X+uM0Y5XwLYZaODqxmMmVoR0ur4Dl/tUtKzVip4vaysk6wTP939glgsRIp7x1uM/MMRljtXtS7gVu6JEfSGnRe7hK45+OGuvBMWyJQ/ii2I/1jKamdFxcRvdM5KWC4p7N1J62wbAZS5s+HsHwjwIpPpKt2atRwNs7rfBmZN7Wu2ZA6zj/ShRRhSyHr9yJpC20t65qIV2ZjO5WiXXzR+gIAjTXhA/uxkC7pnC
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-100"
      name: telegraf-mqtt-credentials
      namespace: telegraf
    type: Opaque
