apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 82.13.6
      helm:
        valueFiles:
        - $values/helm-values/kube-prometheus-stack.yaml
    - repoURL: https://github.com/radoslavirha/home-server
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server
      targetRevision: HEAD
      path: k8s-manifests/kube-prometheus-stack
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true