apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-grafana-datasource-loki
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: P8E80F9AEF21F6940
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        jsonData:
          maxLines: 1000
