---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miot-bridge-mqtt-credentials
  namespace: sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    SECRET_MQTT_MIOT_BRIDGE_PASSWORD: AgBPq12eqmAaqA5MzFuDBL0sLYDQUhZa2WD0q/+tWmkD2UMoH+QA6s13osoq8dXcYaN2meWCRKTLrlVqTUmlig7brtE3ikDrAhVt4FcPF/bveECy4UbUFrRq3YYHY11PgcI0eqbQ63nbXaTGG4nlYE5oKDybNlEkEj5AoyztRnUPc14jnYHqYH847UzObORHvH6RGqleqJYeWmTmSz33lirnPm4p7wZEUkUqLQnz8Bz4iC89IJmogeDam7vTGIN6i9p9v+v2v0PPnjtVyaRB5H65uk2KmZTo/4GPcCBq7vidux8U9/STpBBqhBhu+SlzTDGL53SMh+WnD5oFwlqrSFUC5yb88gECeRkQZrAVG3sgA3yiCDiiO3AGA1mqVKtjI+1s0RLbyPGjhPndDKZpg9aL6Wv3zw85acF/eqcitHLrafG6oCF4uPu9fEST2yWvzoWc8vT5zDqYPpDkzzsr/9bxw8MkR1tX/XUhOhJ8NLvoSF7jZllB1L+z2kP6h0SzEc61aBGJicSQ50/CC9veH5J9+Wlhkkl9+JiZDgo+sJpS2aBnMrF6cpOOpvIMRz3vMHuhHmvPbEO+jPZaAnEFW7HQIZTsmHws3PZ8/1jv5FwO4YqmAvudP2ZwGYWKON2MgGhjjbAhKTCuWpGHqMkpC1ak2BGO9YwSReD8kZhmlUVS7v/u3OQxkNBF/3vulAdD06ICHaHfPhr9/VjVmN+CQelf/uFXUWpRPRLCUhu2KQ3MpazWte0QnF6YczOqUwY=
    SECRET_MQTT_MIOT_BRIDGE_USERNAME: AgBgypkH58zmyrUMVfH+cSilLphbyKZ75Wm83SByYSihG6/Nub2Qf3ESkBg5MxtEky/hWtRU+pOCeVLrqaOzjU8WBTU4BwPNcPLwsCEJq5yItXwFuqms9JDW++wnoD0ruB03DPpIHSwYjHS7b5+a1kCxw/tAkhY3HVLcAKwdQ2LwwONdxFJGzkWoM0+6vFQZJDgm6p+xNUhsnJ1uPdGg8BfESD0i+W7lKCAt4G3Na+vyAeVzLdtFtgFGixKhbF4dic5w85QGV0fnLk++D8LmoEY7gUCpO0usGiLWih3SYmOnWLRnDRLPKdJhwT5K6BJoPSq1lbZY9caRXLUOGnJMuwgCL1Znc2Q4XF7ikAvR75tPuZlxi3y2G/GGJ+ofnlXbTUUuHecTZ7piR8HWycod+LAKQfas28gMT7R48VBJ++pW6FlCgfLNojp2Vusc4u8FjfaBUs0muGP40iRCSP/5xxIlVcfmdUak9jsWq/MHBHGMN5VFPmjPuXEcivxJ6LCbWOu9C4k+l0UBRBGD1N0Mo/RLLE7hqdlyOn4xLc+MTsnn7mTo1wt3kro9IlH7r45I7BaNHHf1W4ib6Byp2yfP5Wqvug/C//j/TsqZzmWij3568JC/5Mn7HEvLMEA65fGjwK1+dsBWVFb3KVl9qf6quapmiHxCugrUfjqS6STxESOdC2nfvv7ilG5RyRGFZrADxuU58v8ocw3tceeMx3tin8NS
  template:
    metadata:
      name: miot-bridge-mqtt-credentials
      namespace: sandbox
    type: Opaque
