---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miot-bridge-api-mqtt-credentials
  namespace: sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    SECRET_MQTT_MIOT_BRIDGE_PASSWORD: AgAp/wJLn+0gMIeqm1nnmzJJGPYKIL5enR8rwua9reZyhpI7eCw4M77zNGY525YQNGc/o3t5xdJTIj444Vun5jOq9Dsi6hbpxB7DUD1e7QBdChEEyZAMRvQxjvcOBcE+TyfKxPIsb5FB60L61XgyiLKkfpb0xnFcdgoLqd3bQcNwzbH4FSV75kktZ/h/OnDuzT8SzTSqxCnnvIB8FmhZr1phH0JMcQTzYcPT/ZYWgjqSm9ztnf1VMRJWzve/orOyxoLnZnT0oTGgxEjKeeldZ07nZs2JSdXbanjkfeS4RtBd0ST+UhJJOqb0K6zRiIrP8mhkzkHW401wAM3iEic9xeFnEch08Fcz053/ZLZA1K2OEfhVS7urfpeeyIeOUWXleW3esd0sUjJy/Y9e51uibYAdV46wixC9dYBhGE8TDOedzIKWaGo69MkTIy1SAvN5XmPJDaNIyoGa5J3WONfrfqMzHPaupAZd19xRX+V5wg2ttaKeZlrU6Bo4EB+kcxze1MLXlHO8n1byhoY+63gKaNXRQddKmrVcB7rnOouqDfgK8isyCHgW+d5yMmivE1uTRMjPh7ZV1GA9q17Mzqamh/ixvHFCljL3drP52xDI3laBkqW0HcZ1RMB3G3Yeq5LEq47lbEFjufLEKE6EERty/DHw9TB6PlTY5ZuZ4TeFdX58EWNuDpfQpURNOO7/1/t1YTwse+Ybg0yXmQVkp4RHy9fgtvtjcx09u7M5GUlQVc8IV7VIQAXFvbGnKisrDg==
    SECRET_MQTT_MIOT_BRIDGE_USERNAME: AgCaXOlWXnuKElMDFcrg09rLv/UsPw3CvwyZSJHfnZgNQevmYaknC5RdNsktYrwsLXGp8G+7yZcVkcweCh6r2msw1KaPaO3krf32kUcQ72Cp+2uRY/TCUUungZrpzfaiIzOA2CuNg9mu0Sqp6piZYUIntetGXeTo3wuA1KTR+ndEcIY5zOpFpb5360LzjJr+IkOaodTf4U4OvRb0w/XvCV4YZMcQfwh/XY8otRnSKnecbIS14ClD/ToXxv6aaFAmYE0lMMQlosIixiWatxkpFgMhgj4WGdJF35KccrW0WFwqWQFKFGKS78Or1sWRtC4FtUVWPw4zMoIvstX94Hm1N4f5N+9NgcI0TC9Ux2zcsYLBY1Xqt9N4Hl60vXig80kbxHUkYxIGZZpnJRGeheSuvC9kPHmhnXQGjuccjvbe1SHWvOSOI/okfm5kjdJXRrsR2yeCj/Ff/+p+yBmcc9/zuMjfKTdDJ0J4vglFawqEjNi4/hMEJYQYXvTajEcQusdjfW8fSAmihNdYO/LjN2jRyeB5VbiEtRuPzaTiS7vvCJrX5RQQ8ROQAfziXdQ94Dv/VAIv9Ep06YRkaojp7CN1mSccRblM5T9B/sslrlhcXQU4AR6048e4RQHmnuNOwkXf5jsOybL4Vgp4WlRR/0AJFfw56hMj/sXp2rXG9Q8VdwU+mx8zlAUecT+LWt3mGnaL00QN+X7+ZKrAV+pjNdTBfjkJ
  template:
    metadata:
      name: miot-bridge-api-mqtt-credentials
      namespace: sandbox
    type: Opaque
