apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.4.0
      helm:
        valueFiles:
        - $values/helm-values/grafana.yaml
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      path: k8s-manifests/grafana
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true