apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.influxdata.com
      chart: influxdb2
      targetRevision: 2.1.2
      helm:
        valueFiles:
        - $values/helm-values/influxdb2.yaml
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      path: k8s-manifests/influxdb2
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true