---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miot-bridge-api-mqtt-credentials
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    SECRET_MQTT_MIOT_BRIDGE_PASSWORD: AgB0Qt5fa3PwxNZddazHa6q71EYtQfFlHH/ZYlD2g90DlB5x5jU/ygnu/JmYmqsUAT3cTt8qpd5x4qBiVUiWrmOjBgwwZDphJcwL82j2canjEPm2S+62/FooJeOTL4A8pz++20ZWhFzVvdg0lI5aKAZn/lSlHIpuOOuBOagYBH39ugYjQIdgUmwfQWMhfcuQIpXL0AFhrAQkQvsX9kULPwys6mDiW8Bo/7ZhRI1VFGBglqESkZSuFrzQsAMMcXJ/zDmUZM4M3ZWdZVD4CFGWmyCFEXHW+aJfyKKbSZf/XdKHrzFlz5/AYJNZ9DGwsmH+qfZ/+LUBSU001v3NIJiJ14GKPL+PR8u0BP6nERez8wrF3tdenpfAHWhyTxE/VvePeVSpBKNUHtb4O5PRs2vIyJuqklIb+N1Y2m1xsLK6F61Ee7o8nP4LJN2vU82lsNPWgGDiVjtxWuZr3pun3yYarzUBtH6zSF+D2AYXw4vZBHKgQrfoJWZFpv7/2QKG1hvAFEFnsanV1rulc+FSx0cjVNTyAailgorhiXCKM/0ds60xvmQEf66l9oxo77uY8fo5RRsUXa6yVfNEWQ56qFY5DmoPHeqEmVOQY4LSNYzebiNaFWLm5eXTTjY6DOadtdEA11Bhj8iEyYiJfq9Qr7B+7alcs/0oq5V1H2oxueBxPrD7mNuV2a+8mC+LggPx+4CVBH51bAg9oKMfKtBnS3ZTC1jIZ1Mz7Qc5CdvmQ04PNl4aPOWiHDoXMerNTpavoQ==
    SECRET_MQTT_MIOT_BRIDGE_USERNAME: AgCHnmjk26XmcGyPr050qcEpPB4zvuhFUcaTXZWaCWWSBN2ERZeRsoM0AZo2N3nf5YW+BC663Ul4p8MDTWOtOMsJuzEGjG8QMqlu+YbuwDeQSuzLGlK2L2pehL3u2X2WxEhn1iM7A8iLoVLIeeeZ0E8VTu+I7Bm87PzRzVPjvBlf3vixcEavmtm3Oe6AX2WtqRFfNL8zq9vm1pr2wD/rmAT9vhGzJjmXDiOlhw0afc0ykyGX+AEvv7mvAJWrgZtQ0Dc+u20kL1zZP1gu8ImEilGkj8y230EcaBXzvD+e+wJcNwAATfDjk3f/Pju86aSuJLhEO7jR64UqJuH3QPzsSvyB3PY5ulz87ReG3nnar0mCThfXHhY2i2Gw/HLma/C7WSGtOfpRV3jz2b6OYtNvoriwT5siBmes+KVvUATENOe3/MEDO4BLS1Mw/P7RHlYOtkkB+uwy2EyCIUepL5os7RrMTfTv387FmQ99yJF/SSA/FPy/MUTET9yCr/LRaD+p4LAes/oQAT8speFfYsHWvgChvLZrvz06w9b/XSooYInUgPgK6MkFniEK8KNRviRBVeGiGrRKr5XDJlgOaY21AjstIKGAl13zUg8OLUxs46otjzu5qNmioUWI1qYjjpV0Ews6DIej23vJ1ezyF1fjFwREEk4nH2KoZWLZ4jN5FOo5/6yywNSmsHRocelyN6t5uM+IFd4kaRM+RBiE5pOKjQbt
  template:
    metadata:
      name: miot-bridge-api-mqtt-credentials
      namespace: production
    type: Opaque
