---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miot-bridge-mqtt-credentials
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    SECRET_MQTT_MIOT_BRIDGE_PASSWORD: AgBRu0urNiJLJMdoCd6E2v0U52385hNGq1y1/5V2MFyXlei3iXoeFkXSJhoyQI1GzVvThyTBKKgTC1qiF25ojTtv1hP4FD7hFoxxoZVAu4cM+xgmKAK2DfEDzzTWX2y7ZAXTVnqb/mm0uDuKb5Lbh1dcFZf40dlz95Ad0wfMBSyezyhTqvUj17fxz7jnRaEBQlLU8EMlYSrEiCiTU/fIg0mBMzcBDU6cU9oQCTiiVE3y0vWIUGv5N3HOOd0t29Jni+raw6uz7JcP1hL047lyPsGV2aqCum48QILnQdw3/T03//53LnCR5AQAarKa4coBDLAl3/PFHS+5K8o4y821N9QcPofTWa9PwhNBe4lU5Wbp+yXDGR0ssSm6M/PmCbwB/8zeh4HMwL4Df7W8MEPjjt2RNGZAdQBxIq7Vkpu2omMcYha9rs3Qf2NZYoej+RhS1x61NNgyUKWaWp3wUrokXplrB02kCSch411tZ9ds78BtbMaOfDgj4aCTm31KgHrES0soc3ZTCn/uZS607XjKtwAmF0ERZmy7f2Pfwi2wnAGJ7nXLke+053UxMa5dMf4ByuUvztB9UKNqPeZMqVwaBIJ0eDF6eHs1yEW06YjvCcw99us4ew2Tzo7BR0xoqJ3ZyaPAqpBJL99MzMbJM9Zzx6uKB5LhQg0sd5smngg5XmGVFZQwVZucqTLhobT35tKwnxQIihDHK7oEwR3ySuZQhTaIAytKDyh/6dl1fBNCUBCnRzHqQ5rMkxH8SdIIsQ==
    SECRET_MQTT_MIOT_BRIDGE_USERNAME: AgDDGK3Z0QR9GUxyi23ZYJyxUHlxAPdsgIUAggGbNyZXmR83aZeBhVLYyejbAO/Mki6WPe5GEHf3MrUHRYpxDgH6WFNxlBAgX58FbdRXd3+0ZNEk9hAoEpxe56UMfCp3pcBwjZq6xwwoW9sASQvzrP28K9yZbJfQpRRpyBVmHJ3SG33J5B983ZrAb835VXsR4xmBoB9Gd4fDvRV3o3ZcObCxQ5d8OqPsLYYAK6b4eCYbKsSL2au5BSTFCTPLVVq9LzhvHJmngpcxVFLtOc/3lYiumNQsRxoEejNi1KtPO/EFT+LC0XiEgOnG/xyvENd8KSiRJan7MtGEcvs8l8Gq7jFNyvlDmi01xxg6/Ww5tx6JzPOKvsb8byqGEAsMZdhx+ZRhqf0S6rKShIq9e0ijvL5QAnRKKNBjKXbkf96HIrPY1vMymuG0HH7QcTW0iMypqCmbW43uQN4MJH7+I8ujuZx24AYAym5SAcc/kiqRm2m1gOddyVfMByk7SEsmm5I72SN84740MHrQ+wBXwAvg6kSITq5GQoC9CG0aIPA1xH0rTNbpaEt0Uv77E1MnLJCH0JA+xhGlGdcTiJDaRpd1pWxYQfZ4JyJXICZPKv9QKN0ZY0iay0Zq4BB4n/NXVlHmZgbEupzwFbXzpzEA3rOHfOFdYlXCt7HDj0BSt2+gkKnab7HH+2gDU4COAdHnk9jQU22E45Y6saQBip7VQk6U/X+Z
  template:
    metadata:
      name: miot-bridge-mqtt-credentials
      namespace: production
    type: Opaque
