apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: 2.40.5
      helm:
        valueFiles:
          - $values/helm-values/argo-rollouts.yaml
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      path: k8s-manifests/argo-rollouts
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true