apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-iot-interactive-map-feeder-production
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      path: helm-charts/iot-applications
      helm:
        releaseName: api-iot-interactive-map-feeder
        valueFiles:
          - $values/helm-values/iot/interactive-map-feeder.yaml
          - $values/helm-values/iot/production/interactive-map-feeder.yaml
          - $values/helm-values/iot/production/variables.yaml
    - repoURL: https://github.com/radoslavirha/home-server.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true