{
 "title": "Loxone",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "rooms",
    "label": "Room",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"loxone\", tag: \"room\")"
    }
   },
   { "name": "longterm", "label": "Long-term" },
   {
    "name": "bucket",
    "query": {
     "query": "import \"array\"\nif \"${longterm}\" == \"true\" then\n  array.from(rows: [{_value: \"loxone_downsample\"}])\nelse\n  array.from(rows: [{_value: \"loxone\"}])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket:\"${bucket}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"loxone_touch\" )\n|> filter(fn: (r) => r._field == \"temperature\")\n|> filter(fn: (r) => r.room =~ /${rooms:regex}/)"
    },
    {
     "query": "lastKnown = from(bucket:\"${bucket}\")\n  |> range(start: -14d, stop: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"loxone_desired\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> filter(fn: (r) => r.room =~ /${rooms:regex}/)\n  |> last()\n\ncurrent = from(bucket:\"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"loxone_desired\" )\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> filter(fn: (r) => r.room =~ /${rooms:regex}/)\n\nunion(tables: [lastKnown, current])\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: true)\n  |> fill(usePrevious: true)"
    },
    {
     "query": "from(bucket:\"${bucket}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"loxone_valve\" )\n|> filter(fn: (r) => r._field == \"open\")\n|> filter(fn: (r) => r.room =~ /${rooms:regex}/)"
    },
    {
     "query": "from(bucket:\"${bucket}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"loxone_valve\" )\n|> filter(fn: (r) => r._field == \"temperature\")\n|> filter(fn: (r) => r.room =~ /${rooms:regex}/)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket:\"${bucket}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"loxone_touch\" )\n|> filter(fn: (r) => r._field == \"humidity\")\n|> filter(fn: (r) => r.room =~ /${rooms:regex}/)"
    },
    {
     "query": "lastKnown = from(bucket:\"${bucket}\")\n  |> range(start: -14d, stop: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"loxone_desired\")\n  |> filter(fn: (r) => r._field == \"humidity\")\n  |> filter(fn: (r) => r.room =~ /${rooms:regex}/)\n  |> last()\n\ncurrent = from(bucket:\"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"loxone_desired\" )\n  |> filter(fn: (r) => r._field == \"humidity\")\n  |> filter(fn: (r) => r.room =~ /${rooms:regex}/)\n\nunion(tables: [lastKnown, current])\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: true)\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket:\"${bucket}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"loxone_valve\" )\n|> filter(fn: (r) => r._field == \"battery\")\n|> filter(fn: (r) => r.room =~ /${rooms:regex}/)"
    }
   ]
  }
 ]
}