---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana-auth-datasource-influxdb2
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    INFLUX_DB_2_TOKEN: AgA+juCUT6w+cmWOjz7+wzN+ab1I2xCtGzE8/0/xTecTB7qjKlVuJhmJ/L9wYSWJ0nRuv23XQh0JdaSRVNBXQ5ZFNZzWKJoUhZ0zvXcJRkBOAd8hwhh12VG7btHXso3VXZ+aF34v7T+ff4U4G435xo8nz4Sb/T8DF8/Sr6Zun1fz2Zqb3DeIPPdtuVO86RLtg1hrTu6bWkLDjbnyhdqadaRLyxrSHD1r9zw0lyHKwX5TckapHDcDZZbpyXyNzr5wS8gKWvqJpmw3win2sC91kDwcFYTWSDotrT8ylwk6ucs4HCLjshcARIBE+7v7VB7HvqlE70y6LBZyAsLDys22xdJlkOsn/pR5WglgTev7PROwmvMJIpvjW/TJEGk5om8yiDB/0b3pBJil7uuQc7hnOrQNWsburDM2fqujd9M8diwb39SjwGxHWxCYAvR+yHS8Lazrphl6y8JW8mz2ABt7/Mx4qzAz7odEeayg20FR795KCkQP3aEZSVwL8T0/fRrvGZvrn+ix3ylfrNZv9YsMKFc8tyYxhFigZKPtVqLMgZMipHcWj5ufAs2KNVLW1uE4rLnwCT7rC0ooeDI7cXsRL2wPYXjblfkdvbL1JitzuiHtxltj5wi3s4RQvTtpN7fb8WKROx1E/CvXTboaXRplszWlBAOIE4lmiFu8kKDkaPztvYP6XQVhAkEAOKVVLbxXykC/FQi26nIKvQyIosfFAss9c9umiDKuSKjMO1M1UKHMzD+5nJmobZoEvsnB3OKWwiOvGdApONbCl5YzzfGZHO9piOMwY/z8HA4hLVLCnRWUNytNT1F9swA/9PHR5JA0I0KBB5UWpy/jmAt1bbFWWjUnXdAkigMOlkOvv2YjNOSX0m3ty84GfGXYWYEvY8Ewiml3mSZSZ6tSWjpZmNLo/lRpP0+VS3jbuhhzcV4hv6c9grbZeqrLu531KfWpQhwABExLJfrgVdTVBFSh+mQf3fh+O7kDUtdpVsEqSvdxpBh/RSi4qrh7aKi+B37yBqCZ8fwqdwpWRsbOelhjbva1qNZ8Y6owC3vJSrxsMpbymTpEh6TZB+xLQfQgzMtnN4CDAkLPQsJWD4zyCZlqQKNza7L6Sg34KPAjHNKd3rBPoDSYhIsUrQxLauNocFAzyJDbtbFwel/k0PmjHOGS88mWmB7DO8IcNOW5Z74uFk6q3XDTyTVFtdfE/FpAG2nSnXaqe2qX8lF8unXPoujexZZLOc5BYUn56tt842iea5f09uhRXY7GHKUuXs+YSa9L3zfyr8zrd2C0GJeC/Wko2+mmcQDNvKHSQw2sq9oey14RahkP+yk+IW88XZmd7dEGZiIkB4MqHnH4a3l6P13/4iHZOfPRJcAYgWay+ixAUkAUQr34bJmUjBH4+is3e0kD+C5k7/MIRdPnSD7jT+zboGWLcfTzbgTe1dGU8mbJue6YSbcG2rdbq2c=
  template:
    metadata:
      name: kube-prometheus-stack-grafana-auth-datasource-influxdb2
      namespace: monitoring
    type: Opaque
