---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana-auth-datasource-influxdb2
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    INFLUX_DB_2_TOKEN: AgAG/tcPHd2mdeVrurx+mP1+9rfDmyLSERITjQiEraURJEDUWFlwGBZetV1+xBbc/Iv7dDoVsVe/1vNK8MMfXZYxQ+4+13AL9c/23KWhSyGnDSgTzFDSiyZwnuCr9Sta07MRm3DC8ycJQkmAZSd+9Qdzt9+onnUC4iL8mnz9/yVCMnozbIc4kltIXjnvRG/nYJr6O7wEV2vSaq3lj0f6iEz+OL//ndcmcJRAja6nWif8Y+R9mwullWGUyc5b+r+fS10aFojKMrFQLbx9yluz7iiq4NlEF+OCY48XZqe/50tNEQbLK+N6O9Qzw5+3fhC6QnK9zzZqhMirZNAdhQXsiScrfjk90Y6duLMSA1HsTAGoI38Q+ODr6+VcLwB8kjKzMjNKxXt7tNnvCrdIX9z7F59WKNQkaOkAwG5zhHZyWKy3jtEMOdOHOVqMZdQ07A/62X1Zex5DRGWkTFZWf/FpNEXeCevxxYmPAH5t+VSK8f9gvE+jLJQSOn5XZAZp4UoTBX9M9wksdqK6dBrhX7InHOaL98YrPvO0q2R0H68PHsDE4y3U5Frbw7Kb+fq1E4Rg9oi8TfO9PamTuXMepEKM3P5M0zLNtE9ttMUClZLnjLEg33Vtd+H2eamZXSRAWmA9dODY0OW8m0bVyuapDLJSbzWdIRQri8uwYXE0cd0llkh9k9s3xAnrOEk+juZQo++DaZ7hou9pnu+98J92+alpx4XIYaWuviyKJrVcmo6z9259eFkrg5+cPW7YnKMJC9plsG1Hua9TCoogdFlWT38V6sxivN8jiTeI01/h4tbEzJjdHmic9R6++C65
  template:
    metadata:
      name: kube-prometheus-stack-grafana-auth-datasource-influxdb2
      namespace: monitoring
    type: Opaque
