---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana-auth-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    admin-password: AgBBT9CBizgOaLabu/PtYo2tOZ4JidXKBTPydBafbT4H/nkWrLsLSzHe/zR0A+dgTYanKitfknTRQYo9qF0m+oMqIHhsQ3FQwqVoMPZdBU29IW+2ov5T+rsCwWH7tctnxbFnSjbXl2zXkLHPYdAHhdFVr5QcONiTz/TwcJPZOk1fOw3S2FNIdRYqB9uTfnKYmHXICx0MyHX7lv//Wm3iJzXTTSwqM4ynYbgNJDLZZQZMhEvSxddy8HG1L+0Wxkwr1sC4CAJKKbp91LEQ9XHHX6kPDpGk6ZtKqblMKkeA4hvYho1X0dMj2skywqtr3CXVHXuBYNnxAsyR3cBz8r7SVDQiuno92LokNGO28qQgKNBU94syQCEUt0MOBUYMQaZdO6SdjmOwN8u6NdchRCabwOEFHyWzDQJAriSvv5174J6c6l+hRbqF5Pr6Io27J2FgPQeIt93Ta/4K5+Xq40Ck7ibtW26+L6m4cRa1cU9tO6IanFDW0iKNy8Ph0xCcHp27Z5xEmIQrz+UK/QA0xKITZ6An/CoSwMWNMEj+ChkBH0htm6BC7WluXlBRlG8AdiDdsN0VLyl+F32wembd21xPEGTpVwTb8+fQIg0ESeN4ibW1pMJIpfpy/LlwmodOmdC6qogX8e3efS1tYNvPvGm6r1LkPJyuUKn9BcuYMWt0tsmkDQ+zvbOu+aupJ+t/U8yyb8ObKwMvIQCTzDxnv9Fi/w==
    admin-user: AgBi338FTwxWHNm5NU7hWJSVBHEoTsLBzAYVpEJdmQRXEMCOui3FE4Zw7PW3I11d82gtETpeDqVVajLSLdNMY60P8cj8AOwuvbVdRe/C9duXowQnb9AuvGrTblmUg/4TY0SZXt939sv60A22MgFYgqmb3tAeNj5kACx/ERXSGroVvvMO49+oKpcGALTYsbNx0CbpCfoRnrpK0TyWdfj0lJlZHA+ktJPL+0E82vaTADxMo2yXSlvULpOgPc+XlH+1KEPws/sCBhQGsvzSJTKVb/l0Bn5VrZlVO4JB2dfz8wmme3z51ZrHk8/yahaGx1koAcdtqiKfkkw44E3NtdQfGlO2QCNUzRSYvvApjjYybt+WfQ2lRGzo65GwTTe4GECrRTS00xLtHbUn88pWMgJ1MjX+EgIr3vj4HQ4FZcq1No/PP2if2vsoQwFsuKFIdSLF3u4XeWjf1A8oHTpTOFqOKLwB2+RvcQDLZ4s5UK3AYtLUUwnhO2lO7SNpelBbmR/EXz/c42yZfqsjlgtbS5tC0hN9M7TjxfgBW6mPPdqqQPwh/4KYqTu8OyXvkdoD7jtWOzR8U6zX0qQeY9dpD67fztbjM2QCcSu3AEs4Szdq2PBSKRSmYdbpQ6KBLnTgfosBM5Udhi9d8hu5lvzMriOW9SLZ+V6aDNTP87aKX9+QrKqFvmq2C/pj27m04nBV80Tm3jwmfQtrRg==
  template:
    metadata:
      name: kube-prometheus-stack-grafana-auth-admin
      namespace: monitoring
    type: Opaque