---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana-auth-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    admin-password: AgCbOCwsz8DBwmEFZ1nsmcpZ/7MCsItmjpnMMHv1ovTzpIVDEusBBKwzWnF/GzAXdYmkUwf1FWwTYxjifhf8sA2YwfwRy405FaoVsKIoZxmcVk/DDPLpyxdZQvQK1W1+cU5wnGKRPesJIqiPHxjrvDHhODQLvEU1KFaoq68JTl74un1pn/J0Oud5bU+r4P1Z31gOKs/qWrblKJ8PrgAIzix2lHkdrbvoI02NnsLvubrBL62DVHYIZk5VWec39gfG0sOM1O9LNosQfWJVYVRYXXaIWxMsy16I+/vgaIRUNwDHJ0Iwu6PhiCFp/1d6/WZ6bHVynoqokln+RlQXnOrTRfsCcJMIgN2KTMx0NgSckKYosBpojgERyqQ70LGcEdnf4zoO4w4UNPyAzxNYS4ItUIWuGH6Fk0cx9FX6lGxeLFrKS4PU2OM9b6DrszRzraVqkF/bV0QEnaAIF6TmHPQebmilxUCFUeo+/c/5M8XQbEwZLidxKbWHvIv5OhooT3cDvFyXkqoKFPlDo+NAV79l9ufns4+QKg/P8s8vjxShQ9P808dGn6CN5dw09gffRrD5Tsig+uazWp/fcZgJNQy6BeRtPByL3OUTR9DVshWFo6cGnmC+3gJSGdQygwghLiG44mN9wyiJxSPYcbxIAv5oT5J28jZFRWOc+GiUv5eRP31/F7WozVRXxhNjbtFaiskLzSSgCejIbqsHqM98z0bIWA==
    admin-user: AgCYDGTpBKcRKA0cH0fVMfmxI1/y8kKSv4J8j1RXWaSVoegWk7+O7UBR0lSmxOeMFbya2VSnuhIEj8XG1rvRsP7B+4Ns0zDIBrJRmb3e8Wg43oClFEpeYnoGmSAX0Iuy/LV3toqWQBNRYs6xq8U/FhEk62HmdQRmlUTuFS8yN97astXrb+fdLrCpDk9JL7v00U20vpkJ4pLJYJbCapxjc+1k2hBMz/af6PTtxf8vrSrWFBh8GfFDahw6jiN701/QGuwzxp/Mrp2LNjbvIMhgE+EzbnBAfB4fFzQgLEIi49lP7l8c7vRn8Yi2njJUy5dTPp6tntQG6M+BWPKlp8PeIzPoDDkNtp8fGCKAgRUcxMFhgR3QrYGj85TqGAuDL5t4jphCtI1MPC5rKjvi5TWxGz21FpY4aSEmAZHPuYRyq/tsdyf3SBd9VV/3MGc2x3LL5Zdw9Dw/S65UWq7uUaPSxjuMxk7wZB3I22Y5FGxCa39XcaMxsVxnN5IYU+rs94uqFv7kVHrmzb93LpkI6IJ7VqVkjwwq1fBrD/zSb4zYaiGfjpi4Z+MVRXPro0ogLpRwyJ2Ewoxy86C6Ty8UpGIcR0aeOSgxyZl0Lw3ZJdGqiIW5CxNfZs+V7Ayg1X/4ceZDNDAK3/X0lvP+XK4iX+XKLXsYzemydGgbatexAUEfkx3kTlTbUbohM5CRIm1lP6vI6l7W95/b737uPz9jqNQlOiNFbQEI5zWDd7s=
  template:
    metadata:
      name: kube-prometheus-stack-grafana-auth-admin
      namespace: monitoring
    type: Opaque