---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    mongodb-root-password: AgAVCU5lnUJEjWBiEQ6LbJS0NzIX0dO7Xwqq5P8covf7i9XuTHNt/Lo3C+1xIKoQNBtJ2vv3DJExxM6HtrwJjgOWh4VqUJthhGRzNczT8M2/tInGVYB6cYkdfoKcScFnS4yvvYd1zVcfAFUuPAMOIKbfNOdWsq3Dka+yX+qnWmXtT1MT6VAMG8LjVXx1LaatROw3eifcLYJrRa+Kd1HCpBE/HggyRfyad+afZXytEJrgvcPSR+VEhgR0DaaYf0zM4CzMBGrMlkbzAjPGo6yMuoQMaC7aT2dBX0Zs4U9dXJAzDkkqStH2LAaTlGNcPJCLzDt7od2Q3sjdjEtFevUPCcgatJVR4+nmdKaYVz5ATLD3DSonOsJsM2N3v6Ngm279uy2pKkvZxrv9kJHlg4FkLiuvRM4NSE13NteaQJSqBf5bSmRXTV7M3y7LjXm8v5wrCbJB1yM2piy6gBPuIw7paEUTfxNB1FBk3W/s/U06ueVSDzzq5Bor67xXROHrJaHJlvj1syMQcYbNIDEmwCykjRgMOW+SzSXkFSoATh0x6aVAW+FxNkZxc6enlBdXo6JOCdcLkHGfzNKJR5rghhdHlc5hK3v6IntMtnnqZx7qmJEKnEEnnAZS8kK6DoabKuq+KZbn6c5DNzDfPTQW7eKsWYN8S67EXSdBL47/imPoqyIh5sv6A2Kfala83Mbmq7nKTOlonf/T1sR16UH15MNV4+YFukeSeUp2vNk=
  template:
    metadata:
      name: mongodb
      namespace: mongodb
    type: Opaque
