---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb2
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  encryptedData:
    admin-password: AgBAKIMVGaOihcHUVWFSNhwHSwrg4G1LyJ/8LfW9YshbcXqS0OVO+0/PJhqZy9M/4jHNsKVgVFuVQoUeBgVwFA48Jorii0hHtvNhrQrUO+qHQ5mmIXca2s1e7AQxaXHLCV3ZfM9hmzd6g9poy/zwzIUnmGRse7NH+45BK7krx9aKrc2W/upm1BY3xMZ7NlelS3VNRjnuGNVwdQKOmE3MMMMIN+JqTbcWB0jYFp5OFkSPnLDEaRFE+PXof8jMud3CaXJfchPurv1QvgB+G5Yw7rWoLRB2MdY1yJR3CAgSgNTfpCXW2H3pK88vJbzi5PlxT8eEzewQyUmPzNBXN88u36cJw27M0mrpKYf1c80tTvR/Dlw6vRxKtlrQ8FYZHL2+ZbcWIINFEzKwdDF8l61hen3Q7JMsM0U9GI94FWmWxqSpynHaqheFFkQUYRLXPesYaX8YwT3scVkr1a8wKLrt+H8hNO2yPf1KNKV8q23FustLSRVUIzk0n5d15fFgNM628LiObxts4hEuHVvK265uyvWhcbvyRggy80fELlawtwDZHwHnj9585x1emdCJCOhjfvM68SQbPmriEaLwaYq30GYmhiSwxXEkc5G4K7oIkGl2o8NDA0DdLe/RIab8oWJCC7Qv2D8oUp/FBXvyLmr42xdeF2uN2YZcplp8vCcg93dmOtPgTYS0oB0/G69pitKS4ebtBexlDhyNK2DuZGuRRx50fA==
    admin-token: AgC5XgZOhst/bAcYcBT1gGA/OeoyEkML/u9faMj3dBx8U2yHGXzimw/dKucjz0NCn+MMaCestfANCZiuoSRFZyqFoRFHRT4kq7iajmHdGklUH60XYWeTVYOMN70Zwgok3dmFB/o/oy1Oso1ZBy+4oMmzlRCCvpAtM5J68rPX7osy02KD+mcRo+ZqzPu7pNNrRQ76PXvi2YDw5rOMNpNQJ23SxsNSkryYVvq899qFYD7kR3pTuSUTMkEx/DlPcIarAj70iR0dNhN2mi+Jv8mCOnq5eJMBtK54712qWN2FUB9r1jYcWf0IZcbjsXL5tzdpefi+SH8DdCyJK+hkyZeMD3Q0w4jdW1ZDAGAaq/6GWuW+6lNuq42qCUDCVRI8COJmHPZ2ApbD7EYZw4WzPzrIC7Dqlpv2/snd7cl7XOZQEb026wCGSD3XxkmtQ5RiUlgR9ETnmjtSAIDDIHWBktD36osdKF/Kb+qiE2vSrCqVtwt7SZXh5kyoG1+8h7N5TgF2ACV5qyYIkVmmvFXnsoH2WVwi+3yRAUaxC0ec0dDvQ226D9pLR/ya/Iwq0J2TVBPlywPFb1gwN+PZfyel9W1Qo3yyZizY9G+69+HEm0e+RMFR6GzXeOgNlWONG16EsCBzfM65OF8WIPpVOFiLQ1Gl4ZN94N492YaAcKEDKViStCfGMdxhWkGVFPnSiFgxEmSggYZvpiXvxssh09g9kgF7a0sdVCsiO+E4sRg=
  template:
    metadata:
      name: influxdb2
      namespace: monitoring
    type: Opaque
